<a href="https://colab.research.google.com/github/AI-Engineer-Abhi/Junior-AI-Engineer---Training/blob/main/Task-Day14/NLP_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Section A — Theoretical Questions**

 What is Natural Language Processing (NLP)? Explain in your own words how it acts
as a bridge between human language and computers.

Natural Language Processing (NLP) is a branch of Artificial Intelligence that enables computers to understand, interpret, and generate human language.

It acts as a bridge between humans and computers by converting natural language, such as English or any other spoken language, into a format that computers can understand and process. This allows us to interact with computers using normal language instead of writing complex programming instructions.
ex: chatbots, voice assistants

 Why do computers need NLP to understand human language? Give one real-world
example to support your answer.

Computers process information in the form of numbers and binary data, whereas humans communicate using words, sentences, emotions, and context. Because of this difference, computers cannot naturally understand human language. NLP helps convert text or speech into structured data that machines can analyze and interpret.

A good real-world example is an email spam filter. NLP analyzes the content of emails and identifies words or patterns such as "Congratulations," "Win now," or "Claim your prize." Based on these patterns, it classifies the email as spam or genuine.

 List any four real-life applications of NLP and briefly describe what each one does.

Chatbots and Virtual Assistants – Applications like ChatGPT and Siri understand user queries and provide relevant responses in natural language.

Machine Translation – Services such as Google Translate convert text from one language to another while preserving the meaning.

Spam Email Detection – NLP examines the content of emails to identify spam messages and prevent them from reaching the inbox.

Sentiment Analysis – Businesses analyze customer reviews and social media posts to determine whether opinions are positive, negative, or neutral.

What is a rule-based NLP system? Explain using the spam detection example
(checking if "Congratulations" is present in a message).

A rule-based NLP system works by following predefined rules instead of learning from data. It checks whether specific conditions are satisfied and then performs an action.

For example, suppose we create a rule that says:

If the message contains the word "Congratulations", mark it as Possible Spam.
Otherwise, mark it as Not Spam.

If the message is "Congratulations! You have won a free gift.", the system finds the keyword "Congratulations" and classifies it as spam. This approach is simple and easy to implement but may fail if the spam message uses different words that are not included in the rules.

 List and briefly explain the seven steps of the NLP pipeline, in the correct order.

Collect Text Data – Gather text from sources such as documents, websites, emails, or social media.

Text Cleaning – Remove unwanted characters, punctuation, HTML tags, emojis, and special symbols to make the text cleaner.

Convert to Lowercase – Convert all text to lowercase so that words like "Phone" and "phone" are treated as the same word.

Tokenization – Split the text into smaller units called tokens, usually words or sentences.

Remove Stopwords – Remove commonly used words such as "the," "is," and "and" because they usually add little meaning.

Feature Extraction – Convert text into numerical features using methods like Bag of Words or TF-IDF so that machine learning models can process it.

Model Building and Prediction – Train a machine learning model on the processed data and use it to make predictions such as spam detection or sentiment classification.

 What is tokenization? Why is it a necessary step before a machine learning model
can process text?

Tokenization is the process of splitting text into smaller units called tokens. These tokens are usually individual words but can also be sentences or characters.

For example:

Sentence: "I love Artificial Intelligence."

Tokens: ["I", "love", "Artificial", "Intelligence"]

Tokenization is necessary because machine learning models cannot understand complete sentences directly. Breaking text into tokens makes it easier to analyze, count word frequencies, and convert text into numerical features for model training.

 What are stopwords? Give three examples of stopwords in English and explain why
they are usually removed.

Stopwords are common words that appear frequently in a language but usually do not add significant meaning to the text during analysis.

Examples of English stopwords are:

the
is
and

These words are usually removed because they occur very often and do not help distinguish one document from another. Removing them reduces unnecessary data, improves processing speed, and allows the model to focus on more meaningful words.

Why is it important to convert all text data to lowercase before processing it in NLP?
Illustrate with an example.

Converting text to lowercase ensures that words with different capitalizations are treated as the same word. This reduces duplicate entries and improves the accuracy of text analysis.

For example, consider the sentence:

"Phone phone PHONE"

Without converting to lowercase, the computer treats them as three different words:

Phone
phone
PHONE

After converting to lowercase:

phone
phone
phone

List any four common mistakes beginners make while working with pandas for NLP
tasks, as covered in the module.

Forgetting to convert text to lowercase before processing.

Using = instead of == while filtering DataFrame rows.

Applying string functions to columns that contain missing (NaN) values without handling them.

Using the wrong column name or incorrect capitalization, which leads to errors such as KeyError.

Explain the difference between using = and == while filtering rows in a DataFrame,
and why mixing them up causes errors.

The operator = is used for assignment, which means it assigns a value to a variable. The operator == is used for comparison, which checks whether two values are equal.

For example, to filter positive reviews:

df[df["Sentiment"] == ["Positive"]
Here, == checks each row to see whether the value in the Sentiment column is "Positive".

If we mistakenly write:
df[df["Sentiment"] = ["Positive"]
Python produces a syntax error because = cannot be used for comparison inside a filtering condition. Mixing these two operators is a common beginner mistake and prevents the program from running correctly.

**Section B — Practical Questions**

 Write a Python program to store the sentence "I love Artificial Intelligence" in a
variable and print its data type using type().

In [1]:
sentence = "I love Artificial Intelligence"
print(type(sentence))

<class 'str'>

Write a Python program to count the total number of characters in the sentence "I love
NLP" using len().

In [2]:
sentence = "I love NLP"
print(len(sentence))

10

 Write a Python program that splits the sentence "I love Natural Language Processing"
into a list of words and prints how many words it contains.

In [3]:
sentence = "I love Natural Language Processing"
words = sentence.split()
print(words)
print(len(words))

['I', 'love', 'Natural', 'Language', 'Processing']
5

 Write a Python program using the in operator to check whether the word "free" is
present in the message "You have won a free prize".

In [4]:
message = "You have won a free prize"
print("free" in message)

True

 Write a Python program that checks if the word "Congratulations" is present in a
message, printing "Possible Spam" if it is and "Not Spam" otherwise.

In [5]:
message = "Congratulations! You have won a prize"

if "Congratulations" in message:
  print("Possible Spam")
else:
  print("Not Spam")

Possible Spam

Write Python code using pandas to create a DataFrame with two columns, "Review"
and "Sentiment", containing at least four sample rows.

In [6]:
import pandas as pd

data = {
    "Review": ["Amazing Product", "Terrible Experience", "Great Value", "Disappointed"],
    "Sentiment": ["Positive", "Negative", "Positive", "Negative"]
}

df = pd.DataFrame(data)
print(df)

                Review Sentiment
0      Amazing Product  Positive
1  Terrible Experience  Negative
2          Great Value  Positive
3         Disappointed  Negative

Write Python statements to display the shape of a DataFrame using df.shape and its
summary using df.info().

In [7]:
print(df.shape)
print("\n")
print(df.info())

(4, 2)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Review     4 non-null      object
 1   Sentiment  4 non-null      object
dtypes: object(2)
memory usage: 196.0+ bytes
None

 Write Python statements to display the first five and last five rows of a DataFrame
using df.head() and df.tail().

In [8]:
print(df.head(5))
print("\n")
print(df.tail(5))

                Review Sentiment
0      Amazing Product  Positive
1  Terrible Experience  Negative
2          Great Value  Positive
3         Disappointed  Negative


                Review Sentiment
0      Amazing Product  Positive
1  Terrible Experience  Negative
2          Great Value  Positive
3         Disappointed  Negative

 Write a Python statement that uses value_counts() to count how many Positive and
Negative entries exist in a "Sentiment" column.

In [9]:
print(df["Sentiment"].value_counts())

Sentiment
Positive    2
Negative    2
Name: count, dtype: int64

Write a Python statement using str.lower() to convert all entries in a "Review" column
of a DataFrame to lowercase.

In [10]:
df["Review"] = df["Review"].str.lower()
print(df)

                Review Sentiment
0      amazing product  Positive
1  terrible experience  Negative
2          great value  Positive
3         disappointed  Negative

 Write a Python statement using df["Review"].apply(len) to add a new "Length" column
showing the character count of each review.

In [11]:
df["Length"] = df["Review"].apply(len)
print(df)

                Review Sentiment  Length
0      amazing product  Positive      15
1  terrible experience  Negative      19
2          great value  Positive      11
3         disappointed  Negative      12

 Write a Python program using a for loop to print every review in a DataFrame column
called "Review", one at a time.

In [12]:
for reviews in df["Review"]:
  print(reviews)

amazing product
terrible experience
great value
disappointed

 Write a Python statement using str.contains() to check whether the word "phone"
appears in each row of a "Review" column.

In [13]:
df["Review"].str.contains("phone")

0    False
1    False
2    False
3    False
Name: Review, dtype: bool

Write a Python statement to filter and display only the rows in a DataFrame where the
"Sentiment" column equals "Positive".

In [14]:
df[df["Sentiment"] == "Positive"]

            Review Sentiment  Length
0  amazing product  Positive      15
2      great value  Positive      11

 Write a Python statement using str.len() to add a "Characters" column showing the
character count of each review.

In [16]:
df["Character"] = df["Review"].str.len()
df

                Review Sentiment  Length  Character
0      amazing product  Positive      15         15
1  terrible experience  Negative      19         19
2          great value  Positive      11         11
3         disappointed  Negative      12         12

 Write a Python statement using apply(lambda x: len(x.split())) to add a "Words"
column showing the word count of each review.

In [18]:
df["Words"] = df["Review"].apply(lambda x: len(x.split()))
df

                Review Sentiment  Length  Character  Words
0      amazing product  Positive      15         15      2
1  terrible experience  Negative      19         19      2
2          great value  Positive      11         11      2
3         disappointed  Negative      12         12      1

 Create a dataset of six movie reviews with a Sentiment column, then write code to
display only the negative reviews.

In [19]:
data = {
    "Review": ["Wonderful", "awful", "awesome", "bad", "fantastic", "horrible"],
    "Sentiment": ["Positive", "Negative", "Positive", "Negative", "Positive", "Negative"]
}

df = pd.DataFrame(data)
df[df["Sentiment"] == "Negative"]

     Review Sentiment
1     awful  Negative
3       bad  Negative
5  horrible  Negative

 Using the movie review dataset from the previous question, write code to find the
longest review based on its character length.

In [24]:
df["Character"] = df["Review"].str.len()
max_length = df["Character"].max()
display(df[df["Character"] == max_length][["Review", "Character"]])

      Review  Character
0  Wonderful          9
4  fantastic          9

 Write code to count how many positive and how many negative reviews exist in your
six-review movie dataset using value_counts().

In [28]:
print(df["Sentiment"].value_counts())

Sentiment
Positive    3
Negative    3
Name: count, dtype: int64

 Create a dataset of 10 student feedback comments labeled Positive or Negative, then
write code to display the first five and last five records.

In [31]:
data = {
    "feedback": ["Excellent", "Terrific", "Magnificent", "Bad", "Worst", "Not Bad", "Good", "Great", "Super", "Terrible"],
    "sentiment": ["Positive", "Positive", "Positive", "Negative", "Negative", "Positive", "Positive", "Positive", "Positive", "Negative"]
}

df = pd.DataFrame(data)
df

      feedback sentiment
0    Excellent  Positive
1     Terrific  Positive
2  Magnificent  Positive
3          Bad  Negative
4        Worst  Negative
5      Not Bad  Positive
6         Good  Positive
7        Great  Positive
8        Super  Positive
9     Terrible  Negative

In [33]:
print(df.head(5))
print("\n")
print(df.tail(5))

      feedback sentiment
0    Excellent  Positive
1     Terrific  Positive
2  Magnificent  Positive
3          Bad  Negative
4        Worst  Negative


   feedback sentiment
5   Not Bad  Positive
6      Good  Positive
7     Great  Positive
8     Super  Positive
9  Terrible  Negative